# SPDX-FileCopyrightText: 2026 Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
# SPDX-License-Identifier: CC-BY-4.0

# Definition of feedstocks


# Definition of "crude_oil" 
Feedstock "crude_oil" {	
}

# Definition of "demineralized_water" 
Feedstock "demineralized_water" {	
}

# Definition of "carbon_dioxide_biogenic" 
Feedstock "carbon_dioxide_biogenic" {
}

# Definition of "organic_wet_waste"
Feedstock "organic_wet_waste" {
}

# Definition of "dry_wood_biomass"
Feedstock "dry_wood_biomass" {
}

# Definition of feedstock "natural_gas"
Feedstock "natural_gas" {
}
