# SPDX-FileCopyrightText: 2026 Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
# SPDX-License-Identifier: CC-BY-4.0

# Definition of the pilot fuel tanks.  

Tank "pilot_oil" { 			
	FuelTypes = OIL
	Size = 2000 	
}

# Definition of main fuel tanks

Tank "main_oil" { 			
	FuelTypes = OIL
	Size = 9000 	
}

Tank "main_methane" { 			
	FuelTypes = METHANE 			
	Size = 9000 	
}

Tank "main_methanol" { 			
	FuelTypes = METHANOL 			
	Size = 9000 	
}

Tank "main_ammonia" { 			
	FuelTypes = AMMONIA 			
	Size = 9000 	
}
