# SPDX-FileCopyrightText: 2026 Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
# SPDX-License-Identifier: CC-BY-4.0

# Curve definitions for initial technology uptake

Curve "uptake_exhaust_gas_boiler_ae_bulk_carrier_handy" {
	Table = [
		0	0.125
		30	0.125
	]
}

Curve "uptake_hull_painting_bulk_carrier_handy" {
	Table = [
		0	0.1
		30	0.1
	]
}

Curve "uptake_lighting_system_bulk_carrier_handy" {
	Table = [
		0	0.5
		30	0.5
	]
}

Curve "uptake_propeller_improvement_devices_bulk_carrier_handy" {
	Table = [
		0	0.25
		30	0.25
	]
}

Curve "uptake_variable_frequency_drive_bulk_carrier_handy" {
	Table = [
		0	0.25
		30	0.25
	]
}
