# SPDX-FileCopyrightText: 2026 Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
# SPDX-License-Identifier: CC-BY-4.0

# Curve definitions for initial age distributions and technology shares

Curve "age_dist_bulk_carrier_handysize_oil" {
	Table = [
		0	0
		1	0
		2	0
		3	0.167
		4	0
		5	0
		6	0
		7	0
		8	0
		9	0
		10	0
		11	0.167
		12	0
		13	0
		14	0
		15	0.167
		16	0.167
		17	0.167
		18	0
		19	0
		20	0
		21	0.167
		22	0
		23	0
		24	0
	]
}
