# SPDX-FileCopyrightText: 2026 Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
# SPDX-License-Identifier: CC-BY-4.0

Curve "age_dist_ammonia_electro_alkaline_africa" {
	Table = [
		0	0.266
		1	0.04
		2	0.693
		3	0
		4	0
		5	0
		6	0
		7	0
		8	0
		9	0
		10	0
		11	0
		12	0
		13	0
		14	0
		15	0
		16	0
		17	0
		18	0
		19	0
		20	0
		21	0
		22	0
		23	0
		24	0
		25	0
		26	0
		27	0
		28	0
		29	0
		30	0
	]
}
