# SPDX-FileCopyrightText: 2026 Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
# SPDX-License-Identifier: CC-BY-4.0

Curve "age_dist_methanol_electro_alkaline_europe" {
	Table = [
		0	0
		1	0.002
		2	0
		3	0
		4	0.076
		5	0
		6	0
		7	0.864
		8	0
		9	0
		10	0
		11	0
		12	0.058
		13	0
		14	0
		15	0
		16	0
		17	0
		18	0
		19	0
		20	0
		21	0
		22	0
		23	0
		24	0
		25	0
		26	0
		27	0
		28	0
		29	0
		30	0
	]
}
