# SPDX-FileCopyrightText: 2026 Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
# SPDX-License-Identifier: CC-BY-4.0

Curve "container_1500_teu_propulsion_load" {
	Table = [
		 5.5	 0.46
		 6.5	 0.65
		 7.5	 0.89
		 8.5	 1.18
		 9.5	 1.54
		10.5	 1.97
		11.5	 2.48
		12.5	 3.09
		13.5	 3.83
		14.5	 4.71
		15.5	 5.77
		16.5	 7.06
		17.5	 8.65
		18.5	10.63
		19.5	13.18
	]
	
	Extrapolate = LINEAR
}
