# SPDX-FileCopyrightText: 2026 Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from collections.abc import Callable, KeysView
from typing import TYPE_CHECKING, Iterable

import numpy as np

from navigate.core.misc import EMPTY_FLOAT
from navigate.core.profiles._base_profile import _BaseProfile
from navigate.core.profiles._container_util import register_tuple_dict_getters
from navigate.util import divide_nonzero, unique_list

if TYPE_CHECKING:
    from navigate.fuel import Emission, Fuel


class _PolicyProfile(_BaseProfile):
    def __init__(self):
        super().__init__()

        # constants
        self._GWP: dict[str, float] = {}                      # global warming potential of emission

        # fuel properties
        self._lower_heating_value: dict[str, float] = {}      # lower heating value, GJ/ton

        # policy specific emission factors
        self._emission_factor_WTT: dict[tuple[str, str], np.ndarray] = {}      # ton emission/ton fuel
        self._emission_factor_TTW: dict[tuple[str, str], np.ndarray] = {}      # ton emission/ton fuel

        # offsetting
        self._offsetting_units: np.ndarray = EMPTY_FLOAT      # ton emissions/year, physically offset emissions
        self._offsetting_expenses: np.ndarray = EMPTY_FLOAT   # USD/year, total expenses from purchasing offsets

    def _initialize_policy_profile(self, fuels: Iterable[Fuel], emissions: Iterable[Emission],
                                   emissions_lifetime: float) -> None:

        for emission in emissions:
            self._GWP[emission.get_name()] = emission.global_warming_potential.get(emissions_lifetime)

        for fuel in fuels:
            self._lower_heating_value[fuel.get_name()] = fuel.lower_heating_value.get()

        self._emission_factor_WTT = self._default_tuple_dict(self._lower_heating_value, self._GWP)
        self._emission_factor_TTW = self._default_tuple_dict(self._lower_heating_value, self._GWP)

        self._offsetting_units = self._default_array()
        self._offsetting_expenses = self._default_array()

    def set_offsetting_units(self, idx: int, units: float) -> None:
        self._offsetting_units[idx] = units

    def set_offsetting_expenses(self, idx: int, expenses: float) -> None:
        self._offsetting_expenses[idx] = expenses

    def get_offsetting_units(self, idx: int | slice = np.s_[:]) -> np.ndarray:
        return self._offsetting_units[idx]

    def get_offsetting_expenses(self, idx: int | slice = np.s_[:]) -> np.ndarray:
        return self._offsetting_expenses[idx]

    def _emission_factors_to_intensity(
            self, emission_factors: dict[tuple[str, str], np.ndarray]
    ) -> dict[tuple[str, str], np.ndarray]:
        # emissions are converted from ton to g (10^6)
        # and energy is converted from GJ to MJ (10^3),
        # so dividing by 10^3
        return {key: divide_nonzero(value, self._lower_heating_value[key[0]] / 1e3)
                for key, value in emission_factors.items()}

    def set_emission_factor_WTT(self, idx: int, key: tuple[str, str], value: float) -> None:
        self._emission_factor_WTT[key][idx] = value

    def set_emission_factor_TTW(self, idx: int, key: tuple[str, str], value: float) -> None:
        self._emission_factor_TTW[key][idx] = value

    def _get_fuels(self) -> list[str]:
        return unique_list([fuel for (fuel, _) in self._emission_factor_WTT])

    def _get_emissions(self) -> KeysView[str]:
        return self._GWP.keys()

    def _get_fuel_emissions(self) -> KeysView[tuple[str, str]]:
        return self._emission_factor_WTT.keys()

    def _get_total_per_fuel(self, method: Callable, idx: int | slice = np.s_[:]) -> dict[str, np.ndarray]:
        result = method(idx=idx)
        return {fuel: np.add.reduce([v for (f, _), v in result.items() if f == fuel])
                for fuel in self._get_fuels()}

    def _equivalent_emission_factors(
            self, emission_factors: dict[tuple[str, str], np.ndarray]
    ) -> dict[tuple[str, str], np.ndarray]:
        return {key: value * self._GWP[key[1]] for key, value in emission_factors.items()}

    # Emission factor getters generated by factory — see _container_util.py.
    # Uses _get_total_per_fuel for per-fuel aggregation instead of _get_total_method.


# _PolicyProfile emission factor getter registrations (replaces ~100 lines of hand-written methods)
_policy_args = dict(
    gwp_attr='_GWP',
    total_method='_get_total_per_fuel',
    to_intensity='_emission_factors_to_intensity',
    to_equivalent='_equivalent_emission_factors',
)
register_tuple_dict_getters(
    _PolicyProfile, 'emission_factor_WTT', data_attr='_emission_factor_WTT', **_policy_args)
register_tuple_dict_getters(
    _PolicyProfile, 'emission_factor_TTW', data_attr='_emission_factor_TTW', **_policy_args)
register_tuple_dict_getters(
    _PolicyProfile, 'emission_factor_WTW', source_attrs=['_emission_factor_WTT', '_emission_factor_TTW'], **_policy_args)
del _policy_args
