# SPDX-FileCopyrightText: 2026 Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
# SPDX-License-Identifier: CC-BY-4.0

# Description: Default carbon dioxide emissions emitted per ton of methane consumed in a gas-injection internal combustion engine under the EU ETS and FuelEU Maritime regulation.
# Unit: ton methane / ton fuel

Variable "eu_default_methane_carbon_dioxide" {
    Value = 2.75
}
