# SPDX-FileCopyrightText: 2026 Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
# SPDX-License-Identifier: CC-BY-4.0

# Description: Default carbon dioxide emissions emitted per ton of diesel consumed in a diesel-injection internal combustion engine under the EU ETS and FuelEU Maritime regulation.
# Unit: ton methane / ton fuel

Variable "eu_default_diesel_carbon_dioxide" {
    Value = 3.114
}
