# SPDX-FileCopyrightText: 2026 Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
# SPDX-License-Identifier: CC-BY-4.0

# Description: Default nitrous oxide emissions emitted per ton of fuel consumed in a gas-injection internal combustion engine under the EU ETS and FuelEU Maritime regulation.
# Unit: ton nitrous oxide / ton fuel

Variable "eu_default_methane_ice_nitrous_oxide" {
    Value = 0.00011
}
