# SPDX-FileCopyrightText: 2026 Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
# SPDX-License-Identifier: CC-BY-4.0

# Description: Default TTW carbon dioxide emissions emitted per ton of diesel consumed in a diesel-injection internal combustion engine under the FuelEU Maritime regulation.
# Unit: ton emission / ton fuel

Variable "fuel_eu_default_diesel_ice_carbon_dioxide" {
    Value = 3.206
}
