# SPDX-FileCopyrightText: 2026 Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
# SPDX-License-Identifier: CC-BY-4.0

# Description: Default TTW carbon dioxide emissions emitted per ton of FAME consumed in a diesel-injection internal combustion engine under the FuelEU Maritime regulation.
# Unit: ton emission / ton fuel

Variable "fuel_eu_default_fatty_acid_methyl_ester_ice_carbon_dioxide" {
    Value = 2.834
}
