<?xml version="1.0" encoding="UTF-8"?>
<!--
SPDX-FileCopyrightText: 2026 Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
SPDX-License-Identifier: Apache-2.0
-->
<plist version="1.0">
    <dict>
        <key>name</key>
        <string>Navigate</string>
        <key>scopeName</key>
        <string>source.navigate</string>
        <key>fileTypes</key>
        <array>
            <string>nav</string>
            <string>inc</string>
            <string>unc</string>
        </array>
        <key>patterns</key>
        <array>
            <dict>
                <key>match</key>
                <string>#.*</string>
                <key>name</key>
                <string>comment.line.navigate</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(DEFINE|EVENTS|Include|Load|Start|End|ModelDefinition|BunkerLogistics|BunkerOptions|Date|Import|Copy|Converter|Curve|Emission|EmissionReduction|Feedstock|Finance|Fleet|Forecast|Fuel|Levy|Lookup|Matrix|Plant|Port|PowerSystem|Process|Producer|Region|Regulation|Report|ReportFT|ReportTCO|Route|Router|Source|Surface|Tank|Timetable|Transport|Variable|Vessel)\b</string>
                <key>name</key>
                <string>keyword.control.navigate</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(Table|Array)\b</string>
                <key>name</key>
                <string>keyword.other.navigate</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b\d+\b</string>
                <key>name</key>
                <string>constant.numeric.navigate</string>
            </dict>
            <dict>
                <key>match</key>
                <string>[{}]</string>
                <key>name</key>
                <string>punctuation.section.braces.navigate</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\(|\)</string>
                <key>name</key>
                <string>punctuation.section.parens.navigate</string>
            </dict>
            <dict>
                <key>match</key>
                <string>=</string>
                <key>name</key>
                <string>keyword.operator.assignment.navigate</string>
            </dict>
            <dict>
                <key>match</key>
                <string>("([^"]*)"|'([^']*)')</string>
                <key>name</key>
                <string>string.quoted.navigate</string>
            </dict>
        </array>
    </dict>
</plist>
