# SPDX-FileCopyrightText: 2026 Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
# SPDX-License-Identifier: CC-BY-4.0

Import Fleet "bulk_carrier_26k_dwt"
Import Fleet "bulk_carrier_52k_dwt"
Import Fleet "bulk_carrier_80k_dwt"
Import Fleet "bulk_carrier_200k_dwt"

Import Fleet "container_1500_teu"
Import Fleet "container_4500_teu"
Import Fleet "container_8000_teu"
Import Fleet "container_15000_teu"

Import Fleet "cruise_25k_gt"
Import Fleet "cruise_100k_gt"
Import Fleet "cruise_175k_gt"

Import Fleet "ferry"

Import Fleet "gas_carrier_100k_cbm"

Import Fleet "general_cargo"

Import Fleet "offshore"

Import Fleet "other"

Import Fleet "roro_4000_ceu"
Import Fleet "roro_7000_ceu"

Import Fleet "tanker_7500_dwt"
Import Fleet "tanker_47k_dwt"
Import Fleet "tanker_127k_dwt"
Import Fleet "tanker_300k_dwt"

Import Fleet "tug"
