# SPDX-FileCopyrightText: 2026 Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
# SPDX-License-Identifier: CC-BY-4.0

Copy Plant "plant_ammonia_blue" "plant_ammonia_blue_africa"
Copy Plant "plant_ammonia_blue" "plant_ammonia_blue_americas"
Copy Plant "plant_ammonia_blue" "plant_ammonia_blue_asia"
Copy Plant "plant_ammonia_blue" "plant_ammonia_blue_europe"
Copy Plant "plant_ammonia_blue" "plant_ammonia_blue_middle_east"

Copy Plant "plant_ammonia_electro_alkaline" "plant_ammonia_electro_alkaline_africa"
Copy Plant "plant_ammonia_electro_alkaline" "plant_ammonia_electro_alkaline_americas"
Copy Plant "plant_ammonia_electro_alkaline" "plant_ammonia_electro_alkaline_asia"
Copy Plant "plant_ammonia_electro_alkaline" "plant_ammonia_electro_alkaline_europe"
Copy Plant "plant_ammonia_electro_alkaline" "plant_ammonia_electro_alkaline_middle_east"

Copy Plant "plant_ammonia_electro_pem" "plant_ammonia_electro_pem_africa"
Copy Plant "plant_ammonia_electro_pem" "plant_ammonia_electro_pem_americas"
Copy Plant "plant_ammonia_electro_pem" "plant_ammonia_electro_pem_asia"
Copy Plant "plant_ammonia_electro_pem" "plant_ammonia_electro_pem_europe"
Copy Plant "plant_ammonia_electro_pem" "plant_ammonia_electro_pem_middle_east"

Copy Plant "plant_ammonia_electro_soec" "plant_ammonia_electro_soec_africa"
Copy Plant "plant_ammonia_electro_soec" "plant_ammonia_electro_soec_americas"
Copy Plant "plant_ammonia_electro_soec" "plant_ammonia_electro_soec_asia"
Copy Plant "plant_ammonia_electro_soec" "plant_ammonia_electro_soec_europe"
Copy Plant "plant_ammonia_electro_soec" "plant_ammonia_electro_soec_middle_east"

Copy Plant "plant_methane_electro_alkaline" "plant_methane_electro_alkaline_africa"
Copy Plant "plant_methane_electro_alkaline" "plant_methane_electro_alkaline_americas"
Copy Plant "plant_methane_electro_alkaline" "plant_methane_electro_alkaline_asia"
Copy Plant "plant_methane_electro_alkaline" "plant_methane_electro_alkaline_europe"
Copy Plant "plant_methane_electro_alkaline" "plant_methane_electro_alkaline_middle_east"

Copy Plant "plant_methane_electro_pem" "plant_methane_electro_pem_africa"
Copy Plant "plant_methane_electro_pem" "plant_methane_electro_pem_americas"
Copy Plant "plant_methane_electro_pem" "plant_methane_electro_pem_asia"
Copy Plant "plant_methane_electro_pem" "plant_methane_electro_pem_europe"
Copy Plant "plant_methane_electro_pem" "plant_methane_electro_pem_middle_east"

Copy Plant "plant_methane_electro_soec" "plant_methane_electro_soec_africa"
Copy Plant "plant_methane_electro_soec" "plant_methane_electro_soec_americas"
Copy Plant "plant_methane_electro_soec" "plant_methane_electro_soec_asia"
Copy Plant "plant_methane_electro_soec" "plant_methane_electro_soec_europe"
Copy Plant "plant_methane_electro_soec" "plant_methane_electro_soec_middle_east"

Copy Plant "plant_methanol_electro_alkaline" "plant_methanol_electro_alkaline_africa"
Copy Plant "plant_methanol_electro_alkaline" "plant_methanol_electro_alkaline_americas"
Copy Plant "plant_methanol_electro_alkaline" "plant_methanol_electro_alkaline_asia"
Copy Plant "plant_methanol_electro_alkaline" "plant_methanol_electro_alkaline_europe"
Copy Plant "plant_methanol_electro_alkaline" "plant_methanol_electro_alkaline_middle_east"

Copy Plant "plant_methanol_electro_pem" "plant_methanol_electro_pem_africa"
Copy Plant "plant_methanol_electro_pem" "plant_methanol_electro_pem_americas"
Copy Plant "plant_methanol_electro_pem" "plant_methanol_electro_pem_asia"
Copy Plant "plant_methanol_electro_pem" "plant_methanol_electro_pem_europe"
Copy Plant "plant_methanol_electro_pem" "plant_methanol_electro_pem_middle_east"

Copy Plant "plant_methanol_electro_soec" "plant_methanol_electro_soec_africa"
Copy Plant "plant_methanol_electro_soec" "plant_methanol_electro_soec_americas"
Copy Plant "plant_methanol_electro_soec" "plant_methanol_electro_soec_asia"
Copy Plant "plant_methanol_electro_soec" "plant_methanol_electro_soec_europe"
Copy Plant "plant_methanol_electro_soec" "plant_methanol_electro_soec_middle_east"

Copy Plant "plant_diesel_electro_alkaline" "plant_diesel_electro_alkaline_africa"
Copy Plant "plant_diesel_electro_alkaline" "plant_diesel_electro_alkaline_americas"
Copy Plant "plant_diesel_electro_alkaline" "plant_diesel_electro_alkaline_asia"
Copy Plant "plant_diesel_electro_alkaline" "plant_diesel_electro_alkaline_europe"
Copy Plant "plant_diesel_electro_alkaline" "plant_diesel_electro_alkaline_middle_east"

Copy Plant "plant_diesel_electro_pem" "plant_diesel_electro_pem_africa"
Copy Plant "plant_diesel_electro_pem" "plant_diesel_electro_pem_americas"
Copy Plant "plant_diesel_electro_pem" "plant_diesel_electro_pem_asia"
Copy Plant "plant_diesel_electro_pem" "plant_diesel_electro_pem_europe"
Copy Plant "plant_diesel_electro_pem" "plant_diesel_electro_pem_middle_east"

Copy Plant "plant_diesel_electro_soec" "plant_diesel_electro_soec_africa"
Copy Plant "plant_diesel_electro_soec" "plant_diesel_electro_soec_americas"
Copy Plant "plant_diesel_electro_soec" "plant_diesel_electro_soec_asia"
Copy Plant "plant_diesel_electro_soec" "plant_diesel_electro_soec_europe"
Copy Plant "plant_diesel_electro_soec" "plant_diesel_electro_soec_middle_east"

Copy Plant "plant_methane_bio" "plant_methane_bio_africa"
Copy Plant "plant_methane_bio" "plant_methane_bio_americas"
Copy Plant "plant_methane_bio" "plant_methane_bio_asia"
Copy Plant "plant_methane_bio" "plant_methane_bio_europe"
Copy Plant "plant_methane_bio" "plant_methane_bio_middle_east"

Copy Plant "plant_methanol_bio_gasification" "plant_methanol_bio_gasification_africa"
Copy Plant "plant_methanol_bio_gasification" "plant_methanol_bio_gasification_americas"
Copy Plant "plant_methanol_bio_gasification" "plant_methanol_bio_gasification_asia"
Copy Plant "plant_methanol_bio_gasification" "plant_methanol_bio_gasification_europe"
# there is no market for plants based on forest residues in the middle east

Copy Plant "plant_methanol_bio_smr" "plant_methanol_bio_smr_africa"
Copy Plant "plant_methanol_bio_smr" "plant_methanol_bio_smr_americas"
Copy Plant "plant_methanol_bio_smr" "plant_methanol_bio_smr_asia"
Copy Plant "plant_methanol_bio_smr" "plant_methanol_bio_smr_europe"
Copy Plant "plant_methanol_bio_smr" "plant_methanol_bio_smr_middle_east"

Copy Plant "plant_ethanol_bio" "plant_ethanol_bio_africa"
Copy Plant "plant_ethanol_bio" "plant_ethanol_bio_americas"
Copy Plant "plant_ethanol_bio" "plant_ethanol_bio_asia"
Copy Plant "plant_ethanol_bio" "plant_ethanol_bio_europe"
# no ethanol plant in Middle East (limited crop residue availability)

Copy Plant "plant_fatty_acid_methyl_ester" "plant_fatty_acid_methyl_ester_europe"

# general -------------------------------------------------------
Plant "*" {
	# assume bio-fuels and blue fuels will use the grid for electricity in their processes
	Source = Source("grid")
}

Plant "*electro*" {
	# assume electro-fuels will use stand-alone renewable electricity for their processes
	Source = Source("renewable")
}

# set the regions
Plant "*africa" {
    Region = Region("africa")
}

Plant "*americas" {
	Region = Region("americas")
}

Plant "*asia" {
	Region = Region("asia")
}

Plant "*europe" {
	Region = Region("europe")
}

Plant "*middle_east" {
	Region = Region("middle_east")
}

# assign cost of capital to the specific pathways and regions
Plant "*bio*africa" {
	CostOfCapital = Forecast("cost_of_capital_plant_bio_africa")
}

Plant "*bio*asia" {
	CostOfCapital = Forecast("cost_of_capital_plant_bio_asia")
}

Plant "*bio*americas" {
	CostOfCapital = Forecast("cost_of_capital_plant_bio_americas")
}

Plant "*bio*europe" {
	CostOfCapital = Forecast("cost_of_capital_plant_bio_europe")
}

Plant "*bio*middle_east" {
	CostOfCapital = Forecast("cost_of_capital_plant_bio_middle_east")
}

Plant "*blue*africa" {
	CostOfCapital = Forecast("cost_of_capital_plant_blue_africa")
}

Plant "*blue*asia" {
	CostOfCapital = Forecast("cost_of_capital_plant_blue_asia")
}

Plant "*blue*americas" {
	CostOfCapital = Forecast("cost_of_capital_plant_blue_americas")
}

Plant "*blue*europe" {
	CostOfCapital = Forecast("cost_of_capital_plant_blue_europe")
}

Plant "*blue*middle_east" {
	CostOfCapital = Forecast("cost_of_capital_plant_blue_middle_east")
}

Plant "*electro*africa" {
	CostOfCapital = Forecast("cost_of_capital_plant_electro_africa")
}

Plant "*electro*asia" {
	CostOfCapital = Forecast("cost_of_capital_plant_electro_asia")
}

Plant "*electro*americas" {
	CostOfCapital = Forecast("cost_of_capital_plant_electro_americas")
}

Plant "*electro*europe" {
	CostOfCapital = Forecast("cost_of_capital_plant_electro_europe")
}

Plant "*electro*middle_east" {
	CostOfCapital = Forecast("cost_of_capital_plant_electro_middle_east")
}

Plant "*methyl_ester_europe" {
	CostOfCapital = Forecast("cost_of_capital_plant_bio_europe")
}
