# SPDX-FileCopyrightText: 2026 Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
# SPDX-License-Identifier: CC-BY-4.0

# miscellaneous
Import Feedstock "demineralized_water"

# fossil
Import Feedstock "methanol_grey"
Import Feedstock "natural_gas"

# biomass
Import Feedstock "feedstock_biogas"
Import Feedstock "feedstock_bioethanol_fermentation"
Import Feedstock "feedstock_biomethanol_gasification"
Import Feedstock "used_cooking_oil"

# biogenic
Import Feedstock "carbon_dioxide_biogenic"
