# SPDX-FileCopyrightText: 2026 Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
# SPDX-License-Identifier: CC-BY-4.0

# ammonia
Import Fuel "ammonia_blue"
Import Fuel "ammonia_electro"

# methane
Import Fuel "liquefied_natural_gas"
Import Fuel "methane_bio"
Import Fuel "methane_electro"

# methanol
Import Fuel "methanol_bio"
Import Fuel "methanol_electro"

# ethanol
Import Fuel "ethanol_bio"

# oil
Import Fuel "fossil_fuel_oil"
Import Fuel "fatty_acid_methyl_ester"
Import Fuel "diesel_electro"
