# SPDX-FileCopyrightText: 2026 Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
# SPDX-License-Identifier: CC-BY-4.0

# Description: Distance crop residues are moved from source to bio-ethanol production plant.
# Assumed similar collection radius to forest residues (~80 km).
# Unit: Nautical miles

Forecast "distance_feedstock_bioethanol_fermentation_to_ethanol_plant" {
	Table = [
		"01-01-2025"	43.0 # 80 km in nautical miles
		"01-01-2050"	43.0 # 80 km in nautical miles
	]
}
