# SPDX-FileCopyrightText: 2026 Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
# SPDX-License-Identifier: CC-BY-4.0

# Description: Distance biomass is moved from source to bio-methanol production plant.
# Unit: Nautical miles

Forecast "distance_feedstock_biomethanol_gasification_to_methanol_plant" {
    Table = [
        "01-01-2025"    43.0 # 80 km in nautical miles
        "01-01-2050"    43.0 # 80 km in nautical miles
    ]
}
