# SPDX-FileCopyrightText: 2026 Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
# SPDX-License-Identifier: CC-BY-4.0

# Description: Distance biomass is moved from source to bio-methane production plant.
# Unit: Nautical miles

Forecast "distance_feedstock_biogas_to_methane_plant" {
    Table = [
        "01-01-2025"    100 # 185 km in nautical miles
        "01-01-2050"    100 # 185 km in nautical miles
    ]
}
