# SPDX-FileCopyrightText: 2026 Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
# SPDX-License-Identifier: CC-BY-4.0

# Curve definitions for initial age distributions and technology shares

Curve "age_dist_mainlines_oil" {
	Table = [
		0	0
		1	0
		2	0
		3	0.25
		4	0
		5	0
		6	0.25
		7	0
		8	0
		9	0.25
		10	0
		11	0
		12	0.25
		13	0
		14	0
		15	0
		16	0
		17	0
		18	0
		19	0
		20	0
		21	0
		22	0
		23	0
		24	0
	]
}

Curve "age_dist_mainlines_methanol" {
	Table = [
		0	1
		1	0
		2	0
		3	0
		4	0
		5	0
		6	0
		7	0
		8	0
		9	0
		10	0
		11	0
		12	0
		13	0
		14	0
		15	0
		16	0
		17	0
		18	0
		19	0
		20	0
		21	0
		22	0
		23	0
		24	0
	]
}
