# SPDX-FileCopyrightText: 2026 Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
# SPDX-License-Identifier: CC-BY-4.0

# Tutorial 2 
# This events file defines the timeline for the fleet transition module.
#####################################################################################
# Define the Start below.



# A) TIME STEPS AND END OF TIMELINE
# Define annual time steps below.



# Define the End of the timeline.



### END OF events.inc FILE